---
title: "Afternoon Exercise Stl"
author: "Connor Flynn"
date: "8/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, list = FALSE)
library(tidyverse)
library(here)
library(janitor)
library(skimr)

```

```{r}
# import data frame
stl_lead <- read_delim(here::here("data", "stl_blood_lead.csv"), delim = ";") %>% 
  mutate(pctElevated = str_replace(pctElevated, pattern = ",", replacement = ".")) %>% 
  mutate(pctElevated = as.numeric(pctElevated))





#pctElevated has commas so
# stl_lead <- read_delim(here::here("data", "stl_blood_lead.csv"), delim = ";") %>%  clean_names() %>% 
# mutate(pctElevated = str_replace(pctElevated, pattern = ",", replacement = ".")) %>% 
# mutate(pctElevated = as.numeric(pctElevated))
```

```{r}
# create new data frame with additional column

stl_lead_prop <- stl_lead %>% dplyr::mutate(prop_white = white / totalPop * 100)
stl_lead_prop
```


```{r}
# Create a scatter plot

stl_lead_plot <- ggplot(data = stl_lead_prop, aes(x = prop_white, y = pctElevated)) +
  geom_point(color = "purple", size = 2) +
  theme_classic()
  

stl_lead_plot
```
```{r}
# Save the plot as a jpg

ggsave(here::here("figs", "stl_lead_plot.jpg"), height = 5, width = 6)
```

```{r}
# Create a histogram
pctElevated_plot <- ggplot(data = stl_lead, aes(x = pctElevated)) +
  geom_histogram(color = "black", fill = "blue") +
  theme_minimal()

pctElevated_plot
```

```{r}
# Save the histogram

ggsave(here::here("figs", "stl_lead_plot.png"), height = 5, width = 6)

```

